### PR TITLE
Fix bin override

### PR DESCRIPTION
**Pull request by mkmik**
When the user uses a `"bin": "some/path"` override in the `.arclinter`
config, this extension can no longer spawn the binary to get the version
by using the default binary name.

See https://secure.phabricator.com/book/phabricator/article/arcanist_lint/ in the
`Locating Binaries and Interpreters` section and the docstring for
`ArcanistExternalLinter::getExecutableCommand()`:

```
Get the composed executable command, including the interpreter and binary but without flags or paths. This can be used to execute --version commands.
```

### CODE REVIEW

**Comment by mkmik** [comment]
hey @googlebot 

My employer confirms they signed the CLA. The company name is Bitnami, and I double-checked that this commit has been authored with my mkm@bitnami.com account (which is associated with my mmikulicic github account, although not as a primary email)

**Comment by mkmik** [comment]
I just remembered that when I last had to sign the google CLA while I was working for another company, there was a google group all employees granted contributors rights are supposed to be member of. I'll doublecheck that.

**Comment by mkmik** [comment]
I'm now member of the google group Bitnami used to sign the CLA

**Comment by mkmik** [comment]
friendly ping

**Comment by adarshaj** [comment]
This fixes #1

**Comment by adarshaj** [comment]
Can the collaborator pls review this for a merge? I'm interested in using this.

/cc @jverkoey

**Comment by jverkoey** [comment]
Apologies for this taking so long to merge, I appear to have missed the original batch of notifications.

**Comment by mkmik** [comment]
@jverkoey thanks! would it be possible to merge it into master?

**Pull request merged**
